"""Typed App subclasses generated from the NetBox OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: https://demo.netbox.dev/api/schema/ (NetBox API 4.6.5 (4.6))

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynetbox.app import App

if TYPE_CHECKING:
    from aiopynetbox.endpoint import Endpoint


class CircuitsApp(App):
    circuit_group_assignments: Endpoint
    circuit_groups: Endpoint
    circuit_terminations: Endpoint
    circuit_types: Endpoint
    circuits: Endpoint
    provider_accounts: Endpoint
    provider_networks: Endpoint
    providers: Endpoint
    virtual_circuit_terminations: Endpoint
    virtual_circuit_types: Endpoint
    virtual_circuits: Endpoint


class CoreApp(App):
    background_queues: Endpoint
    background_tasks: Endpoint
    background_workers: Endpoint
    data_files: Endpoint
    data_sources: Endpoint
    jobs: Endpoint
    object_changes: Endpoint
    object_types: Endpoint


class DcimApp(App):
    cable_bundles: Endpoint
    cable_terminations: Endpoint
    cables: Endpoint
    connected_device: Endpoint
    console_port_templates: Endpoint
    console_ports: Endpoint
    console_server_port_templates: Endpoint
    console_server_ports: Endpoint
    device_bay_templates: Endpoint
    device_bays: Endpoint
    device_roles: Endpoint
    device_types: Endpoint
    devices: Endpoint
    front_port_templates: Endpoint
    front_ports: Endpoint
    interface_templates: Endpoint
    interfaces: Endpoint
    inventory_item_roles: Endpoint
    inventory_item_templates: Endpoint
    inventory_items: Endpoint
    locations: Endpoint
    mac_addresses: Endpoint
    manufacturers: Endpoint
    module_bay_templates: Endpoint
    module_bays: Endpoint
    module_type_profiles: Endpoint
    module_types: Endpoint
    modules: Endpoint
    platforms: Endpoint
    power_feeds: Endpoint
    power_outlet_templates: Endpoint
    power_outlets: Endpoint
    power_panels: Endpoint
    power_port_templates: Endpoint
    power_ports: Endpoint
    rack_groups: Endpoint
    rack_reservations: Endpoint
    rack_roles: Endpoint
    rack_types: Endpoint
    racks: Endpoint
    rear_port_templates: Endpoint
    rear_ports: Endpoint
    regions: Endpoint
    site_groups: Endpoint
    sites: Endpoint
    virtual_chassis: Endpoint
    virtual_device_contexts: Endpoint


class ExtrasApp(App):
    bookmarks: Endpoint
    config_context_profiles: Endpoint
    config_contexts: Endpoint
    config_templates: Endpoint
    custom_field_choice_sets: Endpoint
    custom_fields: Endpoint
    custom_links: Endpoint
    dashboard: Endpoint
    event_rules: Endpoint
    export_templates: Endpoint
    image_attachments: Endpoint
    journal_entries: Endpoint
    notification_groups: Endpoint
    notifications: Endpoint
    saved_filters: Endpoint
    scripts: Endpoint
    subscriptions: Endpoint
    table_configs: Endpoint
    tagged_objects: Endpoint
    tags: Endpoint
    webhooks: Endpoint


class IpamApp(App):
    aggregates: Endpoint
    asn_ranges: Endpoint
    asns: Endpoint
    fhrp_group_assignments: Endpoint
    fhrp_groups: Endpoint
    ip_addresses: Endpoint
    ip_ranges: Endpoint
    prefixes: Endpoint
    rirs: Endpoint
    roles: Endpoint
    route_targets: Endpoint
    service_templates: Endpoint
    services: Endpoint
    vlan_groups: Endpoint
    vlan_translation_policies: Endpoint
    vlan_translation_rules: Endpoint
    vlans: Endpoint
    vrfs: Endpoint


class TenancyApp(App):
    contact_assignments: Endpoint
    contact_groups: Endpoint
    contact_roles: Endpoint
    contacts: Endpoint
    tenant_groups: Endpoint
    tenants: Endpoint


class UsersApp(App):
    config: Endpoint
    groups: Endpoint
    owner_groups: Endpoint
    owners: Endpoint
    permissions: Endpoint
    tokens: Endpoint
    users: Endpoint


class VirtualizationApp(App):
    cluster_groups: Endpoint
    cluster_types: Endpoint
    clusters: Endpoint
    interfaces: Endpoint
    virtual_disks: Endpoint
    virtual_machine_types: Endpoint
    virtual_machines: Endpoint


class VpnApp(App):
    ike_policies: Endpoint
    ike_proposals: Endpoint
    ipsec_policies: Endpoint
    ipsec_profiles: Endpoint
    ipsec_proposals: Endpoint
    l2vpn_terminations: Endpoint
    l2vpns: Endpoint
    tunnel_groups: Endpoint
    tunnel_terminations: Endpoint
    tunnels: Endpoint


class WirelessApp(App):
    wireless_lan_groups: Endpoint
    wireless_lans: Endpoint
    wireless_links: Endpoint


APP_CLASSES: dict[str, type[App]] = {
    "circuits": CircuitsApp,
    "core": CoreApp,
    "dcim": DcimApp,
    "extras": ExtrasApp,
    "ipam": IpamApp,
    "tenancy": TenancyApp,
    "users": UsersApp,
    "virtualization": VirtualizationApp,
    "vpn": VpnApp,
    "wireless": WirelessApp,
}
