"""Typed App subclasses generated from the NetBox OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: https://demo.netbox.dev/api/schema/ (NetBox API 4.6.5 (4.6))

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work, and the hint classes in hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynetbox.app import App

if TYPE_CHECKING:
    from aiopynetbox import hints_generated as hints


class CircuitsApp(App):
    circuit_group_assignments: hints.CircuitsCircuitGroupAssignmentsEndpoint
    circuit_groups: hints.CircuitsCircuitGroupsEndpoint
    circuit_terminations: hints.CircuitsCircuitTerminationsEndpoint
    circuit_types: hints.CircuitsCircuitTypesEndpoint
    circuits: hints.CircuitsCircuitsEndpoint
    provider_accounts: hints.CircuitsProviderAccountsEndpoint
    provider_networks: hints.CircuitsProviderNetworksEndpoint
    providers: hints.CircuitsProvidersEndpoint
    virtual_circuit_terminations: hints.CircuitsVirtualCircuitTerminationsEndpoint
    virtual_circuit_types: hints.CircuitsVirtualCircuitTypesEndpoint
    virtual_circuits: hints.CircuitsVirtualCircuitsEndpoint


class CoreApp(App):
    background_queues: hints.CoreBackgroundQueuesEndpoint
    background_tasks: hints.CoreBackgroundTasksEndpoint
    background_workers: hints.CoreBackgroundWorkersEndpoint
    data_files: hints.CoreDataFilesEndpoint
    data_sources: hints.CoreDataSourcesEndpoint
    jobs: hints.CoreJobsEndpoint
    object_changes: hints.CoreObjectChangesEndpoint
    object_types: hints.CoreObjectTypesEndpoint


class DcimApp(App):
    cable_bundles: hints.DcimCableBundlesEndpoint
    cable_terminations: hints.DcimCableTerminationsEndpoint
    cables: hints.DcimCablesEndpoint
    connected_device: hints.DcimConnectedDeviceEndpoint
    console_port_templates: hints.DcimConsolePortTemplatesEndpoint
    console_ports: hints.DcimConsolePortsEndpoint
    console_server_port_templates: hints.DcimConsoleServerPortTemplatesEndpoint
    console_server_ports: hints.DcimConsoleServerPortsEndpoint
    device_bay_templates: hints.DcimDeviceBayTemplatesEndpoint
    device_bays: hints.DcimDeviceBaysEndpoint
    device_roles: hints.DcimDeviceRolesEndpoint
    device_types: hints.DcimDeviceTypesEndpoint
    devices: hints.DcimDevicesEndpoint
    front_port_templates: hints.DcimFrontPortTemplatesEndpoint
    front_ports: hints.DcimFrontPortsEndpoint
    interface_templates: hints.DcimInterfaceTemplatesEndpoint
    interfaces: hints.DcimInterfacesEndpoint
    inventory_item_roles: hints.DcimInventoryItemRolesEndpoint
    inventory_item_templates: hints.DcimInventoryItemTemplatesEndpoint
    inventory_items: hints.DcimInventoryItemsEndpoint
    locations: hints.DcimLocationsEndpoint
    mac_addresses: hints.DcimMacAddressesEndpoint
    manufacturers: hints.DcimManufacturersEndpoint
    module_bay_templates: hints.DcimModuleBayTemplatesEndpoint
    module_bays: hints.DcimModuleBaysEndpoint
    module_type_profiles: hints.DcimModuleTypeProfilesEndpoint
    module_types: hints.DcimModuleTypesEndpoint
    modules: hints.DcimModulesEndpoint
    platforms: hints.DcimPlatformsEndpoint
    power_feeds: hints.DcimPowerFeedsEndpoint
    power_outlet_templates: hints.DcimPowerOutletTemplatesEndpoint
    power_outlets: hints.DcimPowerOutletsEndpoint
    power_panels: hints.DcimPowerPanelsEndpoint
    power_port_templates: hints.DcimPowerPortTemplatesEndpoint
    power_ports: hints.DcimPowerPortsEndpoint
    rack_groups: hints.DcimRackGroupsEndpoint
    rack_reservations: hints.DcimRackReservationsEndpoint
    rack_roles: hints.DcimRackRolesEndpoint
    rack_types: hints.DcimRackTypesEndpoint
    racks: hints.DcimRacksEndpoint
    rear_port_templates: hints.DcimRearPortTemplatesEndpoint
    rear_ports: hints.DcimRearPortsEndpoint
    regions: hints.DcimRegionsEndpoint
    site_groups: hints.DcimSiteGroupsEndpoint
    sites: hints.DcimSitesEndpoint
    virtual_chassis: hints.DcimVirtualChassisEndpoint
    virtual_device_contexts: hints.DcimVirtualDeviceContextsEndpoint


class ExtrasApp(App):
    bookmarks: hints.ExtrasBookmarksEndpoint
    config_context_profiles: hints.ExtrasConfigContextProfilesEndpoint
    config_contexts: hints.ExtrasConfigContextsEndpoint
    config_templates: hints.ExtrasConfigTemplatesEndpoint
    custom_field_choice_sets: hints.ExtrasCustomFieldChoiceSetsEndpoint
    custom_fields: hints.ExtrasCustomFieldsEndpoint
    custom_links: hints.ExtrasCustomLinksEndpoint
    dashboard: hints.ExtrasDashboardEndpoint
    event_rules: hints.ExtrasEventRulesEndpoint
    export_templates: hints.ExtrasExportTemplatesEndpoint
    image_attachments: hints.ExtrasImageAttachmentsEndpoint
    journal_entries: hints.ExtrasJournalEntriesEndpoint
    notification_groups: hints.ExtrasNotificationGroupsEndpoint
    notifications: hints.ExtrasNotificationsEndpoint
    saved_filters: hints.ExtrasSavedFiltersEndpoint
    scripts: hints.ExtrasScriptsEndpoint
    subscriptions: hints.ExtrasSubscriptionsEndpoint
    table_configs: hints.ExtrasTableConfigsEndpoint
    tagged_objects: hints.ExtrasTaggedObjectsEndpoint
    tags: hints.ExtrasTagsEndpoint
    webhooks: hints.ExtrasWebhooksEndpoint


class IpamApp(App):
    aggregates: hints.IpamAggregatesEndpoint
    asn_ranges: hints.IpamAsnRangesEndpoint
    asns: hints.IpamAsnsEndpoint
    fhrp_group_assignments: hints.IpamFhrpGroupAssignmentsEndpoint
    fhrp_groups: hints.IpamFhrpGroupsEndpoint
    ip_addresses: hints.IpamIpAddressesEndpoint
    ip_ranges: hints.IpamIpRangesEndpoint
    prefixes: hints.IpamPrefixesEndpoint
    rirs: hints.IpamRirsEndpoint
    roles: hints.IpamRolesEndpoint
    route_targets: hints.IpamRouteTargetsEndpoint
    service_templates: hints.IpamServiceTemplatesEndpoint
    services: hints.IpamServicesEndpoint
    vlan_groups: hints.IpamVlanGroupsEndpoint
    vlan_translation_policies: hints.IpamVlanTranslationPoliciesEndpoint
    vlan_translation_rules: hints.IpamVlanTranslationRulesEndpoint
    vlans: hints.IpamVlansEndpoint
    vrfs: hints.IpamVrfsEndpoint


class TenancyApp(App):
    contact_assignments: hints.TenancyContactAssignmentsEndpoint
    contact_groups: hints.TenancyContactGroupsEndpoint
    contact_roles: hints.TenancyContactRolesEndpoint
    contacts: hints.TenancyContactsEndpoint
    tenant_groups: hints.TenancyTenantGroupsEndpoint
    tenants: hints.TenancyTenantsEndpoint


class UsersApp(App):
    config: hints.UsersConfigEndpoint
    groups: hints.UsersGroupsEndpoint
    owner_groups: hints.UsersOwnerGroupsEndpoint
    owners: hints.UsersOwnersEndpoint
    permissions: hints.UsersPermissionsEndpoint
    tokens: hints.UsersTokensEndpoint
    users: hints.UsersUsersEndpoint


class VirtualizationApp(App):
    cluster_groups: hints.VirtualizationClusterGroupsEndpoint
    cluster_types: hints.VirtualizationClusterTypesEndpoint
    clusters: hints.VirtualizationClustersEndpoint
    interfaces: hints.VirtualizationInterfacesEndpoint
    virtual_disks: hints.VirtualizationVirtualDisksEndpoint
    virtual_machine_types: hints.VirtualizationVirtualMachineTypesEndpoint
    virtual_machines: hints.VirtualizationVirtualMachinesEndpoint


class VpnApp(App):
    ike_policies: hints.VpnIkePoliciesEndpoint
    ike_proposals: hints.VpnIkeProposalsEndpoint
    ipsec_policies: hints.VpnIpsecPoliciesEndpoint
    ipsec_profiles: hints.VpnIpsecProfilesEndpoint
    ipsec_proposals: hints.VpnIpsecProposalsEndpoint
    l2vpn_terminations: hints.VpnL2vpnTerminationsEndpoint
    l2vpns: hints.VpnL2vpnsEndpoint
    tunnel_groups: hints.VpnTunnelGroupsEndpoint
    tunnel_terminations: hints.VpnTunnelTerminationsEndpoint
    tunnels: hints.VpnTunnelsEndpoint


class WirelessApp(App):
    wireless_lan_groups: hints.WirelessWirelessLanGroupsEndpoint
    wireless_lans: hints.WirelessWirelessLansEndpoint
    wireless_links: hints.WirelessWirelessLinksEndpoint


APP_CLASSES: dict[str, type[App]] = {
    "circuits": CircuitsApp,
    "core": CoreApp,
    "dcim": DcimApp,
    "extras": ExtrasApp,
    "ipam": IpamApp,
    "tenancy": TenancyApp,
    "users": UsersApp,
    "virtualization": VirtualizationApp,
    "vpn": VpnApp,
    "wireless": WirelessApp,
}
