"""Regenerate src/aiopynetbox/apps.py from a NetBox OpenAPI schema.

Usage:

    uv run python scripts/generate_endpoints.py [schema_url]

Defaults to the public demo instance, which runs the latest NetBox
release. The output is deterministic for a given schema, so rerunning
without upstream changes produces no diff.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

import httpx

DEFAULT_URL = "https://demo.netbox.dev/api/schema/"
OUT = Path(__file__).resolve().parent.parent / "src" / "aiopynetbox" / "apps.py"

# List-view paths only: /api/<app>/<endpoint>/. Detail and sub-routes
# (/{id}/, /render-config/, ...) don't match.
LIST_PATH = re.compile(r"^/api/([a-z]+)/([a-z0-9-]+)/$")

# Real attributes on App that an endpoint annotation must never shadow.
RESERVED = {"name", "endpoint"}

HEADER = '''"""Typed App subclasses generated from the NetBox OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: {source} (NetBox API {version})

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynetbox.app import App

if TYPE_CHECKING:
    from aiopynetbox.endpoint import Endpoint
'''


def main() -> None:
    url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URL
    resp = httpx.get(
        url,
        params={"format": "json"},
        headers={"Accept": "application/json"},
        follow_redirects=True,
        timeout=120,
    )
    resp.raise_for_status()
    spec = resp.json()

    apps: dict[str, set[str]] = defaultdict(set)
    for path in spec["paths"]:
        match = LIST_PATH.fullmatch(path)
        if not match:
            continue
        app, slug = match.groups()
        if app == "plugins":
            continue  # plugin endpoints depend on what the instance has installed
        attr = slug.replace("-", "_")
        if attr.isidentifier() and attr not in RESERVED:
            apps[app].add(attr)

    version = spec.get("info", {}).get("version", "unknown")
    chunks = [HEADER.format(source=url, version=version)]
    for app in sorted(apps):
        lines = [f"class {app.title()}App(App):"]
        lines += [f"    {attr}: Endpoint" for attr in sorted(apps[app])]
        chunks.append("\n".join(lines))
    mapping = [f'    "{app}": {app.title()}App,' for app in sorted(apps)]
    chunks.append(
        "APP_CLASSES: dict[str, type[App]] = {\n" + "\n".join(mapping) + "\n}"
    )

    OUT.write_text("\n\n\n".join(chunks) + "\n")
    total = sum(len(v) for v in apps.values())
    print(f"wrote {OUT} ({total} endpoints across {len(apps)} apps, NetBox {version})")


main()
