"""Regenerate the typed endpoint hints from a NetBox OpenAPI schema.

Outputs two files:

- src/aiopynetbox/apps_generated.py - typed App subclasses (endpoint-name hints)
- src/aiopynetbox/hints_generated.pyi - stub-only per-endpoint classes with
  TypedDict-backed kwargs overloads for filter/get/count/create

Usage:

    uv run python scripts/generate_endpoints.py [schema_url]

Defaults to the public demo instance, which runs the latest NetBox
release. The output is deterministic for a given schema, so rerunning
without upstream changes produces no diff.
"""

from __future__ import annotations

import keyword
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import httpx2

DEFAULT_URL = "https://demo.netbox.dev/api/schema/"
SRC = Path(__file__).resolve().parent.parent / "src" / "aiopynetbox"

# List-view paths only: /api/<app>/<endpoint>/. Detail and sub-routes
# (/{id}/, /render-config/, ...) don't match.
LIST_PATH = re.compile(r"^/api/([a-z]+)/([a-z0-9-]+)/$")

# Real attributes on App that an endpoint annotation must never shadow.
RESERVED = {"name", "endpoint"}

# Query params that aren't filters: pagination is driven by all()/the
# client, and lookup variants (name__ic, id__gt...) fall through to the
# Any-kwargs overload rather than multiplying the hint size ~5x.
PARAM_EXCLUDE = {"limit", "offset", "start", "format"}

# Endpoints whose records are model subclasses; hints return those types
# so their helpers (available_ips, sync, ...) type-check.
MODEL_RETURNS = {
    ("core", "data_sources"): "DataSources",
    ("ipam", "ip_ranges"): "IpRanges",
    ("ipam", "prefixes"): "Prefixes",
    ("ipam", "vlan_groups"): "VlanGroups",
}

APPS_HEADER = '''"""Typed App subclasses generated from the NetBox OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: {source} (NetBox API {version})

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work, and the hint classes in hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynetbox.app import App

if TYPE_CHECKING:
    from aiopynetbox import hints_generated as hints
'''

HINTS_HEADER = '''"""Stub-only kwargs hints generated from the NetBox OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: {source} (NetBox API {version})

This module exists only as a stub (.pyi): it is never imported at
runtime, and every runtime endpoint object is a plain Endpoint (or a
models.py subclass). The TypedDicts carry filter-param and writable-
field names for autocomplete; values are Any so nothing is enforced,
and the trailing **kwargs: Any overloads keep custom-field filters
(cf_*), lookup expressions (name__isw=...), and plugin params legal.
"""

from typing import Any, TypedDict, Unpack, overload

from aiopynetbox.endpoint import Endpoint
from aiopynetbox.models import DataSources, IpRanges, Prefixes, VlanGroups
from aiopynetbox.response import Record, RecordSet
'''


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def valid_keys(names: set[str]) -> list[str]:
    return sorted(
        n
        for n in names
        if n.isidentifier()
        and not keyword.iskeyword(n)
        and "__" not in n
        and not n.startswith("cf_")
        and n not in PARAM_EXCLUDE
    )


def schema_properties(schema: dict[str, Any], components: dict[str, Any]) -> set[str]:
    """Property names of a request schema, resolving $ref and allOf."""
    if "$ref" in schema:
        schema = components.get(schema["$ref"].rsplit("/", 1)[-1], {})
    props = set(schema.get("properties", {}))
    for part in schema.get("allOf", []):
        props |= schema_properties(part, components)
    return props


def filter_params(operation: dict[str, Any]) -> set[str]:
    return {
        p["name"] for p in operation.get("parameters", []) if p.get("in") == "query"
    }


def create_fields(operation: dict[str, Any], components: dict[str, Any]) -> set[str]:
    content = operation.get("requestBody", {}).get("content", {})
    schema = content.get("application/json", {}).get("schema", {})
    return schema_properties(schema, components)


def endpoint_stub(app: str, attr: str, filters: list[str], fields: list[str]) -> str:
    """One endpoint's TypedDicts + Endpoint subclass for hints_generated.pyi."""
    cls = f"{app.title()}{pascal(attr)}"
    record = MODEL_RETURNS.get((app, attr), "Record")
    out: list[str] = []
    if filters:
        out.append(f"class {cls}Filters(TypedDict, total=False):")
        out += [f"    {name}: Any" for name in filters]
        out.append("")
    if fields:
        out.append(f"class {cls}Fields(TypedDict, total=False):")
        out += [f"    {name}: Any" for name in fields]
        out.append("")
    out.append(f"class {cls}Endpoint(Endpoint):")
    if filters:
        out += [
            "    @overload",
            f"    def filter(self, **kwargs: Unpack[{cls}Filters]) -> RecordSet: ...",
            "    @overload",
            "    def filter(self, **kwargs: Any) -> RecordSet: ...",
            "    @overload",
            f"    async def get(self, id: int | str, /) -> {record} | None: ...",
            "    @overload",
            f"    async def get(self, **kwargs: Unpack[{cls}Filters]) -> {record} | None: ...",
            "    @overload",
            "    async def get(",
            "        self, id: int | str | None = None, /, **kwargs: Any",
            f"    ) -> {record} | None: ...",
            "    @overload",
            f"    async def count(self, **kwargs: Unpack[{cls}Filters]) -> int: ...",
            "    @overload",
            "    async def count(self, **kwargs: Any) -> int: ...",
        ]
    if fields:
        out += [
            "    @overload",
            f"    async def create(self, **fields: Unpack[{cls}Fields]) -> {record}: ...",
            "    @overload",
            f"    async def create(self, objects: list[dict[str, Any]], /) -> list[{record}]: ...",
            "    @overload",
            "    async def create(",
            "        self, *args: dict[str, Any] | list[dict[str, Any]], **kwargs: Any",
            f"    ) -> {record} | list[{record}]: ...",
        ]
    if not filters and not fields:
        out.append("    ...")
    return "\n".join(out)


def main() -> None:
    url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URL
    resp = httpx2.get(
        url,
        params={"format": "json"},
        headers={"Accept": "application/json"},
        follow_redirects=True,
        timeout=120,
    )
    resp.raise_for_status()
    spec = resp.json()
    components = spec.get("components", {}).get("schemas", {})

    # app -> attr -> (filters, fields)
    apps: dict[str, dict[str, tuple[list[str], list[str]]]] = defaultdict(dict)
    for path, operations in spec["paths"].items():
        match = LIST_PATH.fullmatch(path)
        if not match:
            continue
        app, slug = match.groups()
        if app == "plugins":
            continue  # plugin endpoints depend on what the instance has installed
        attr = slug.replace("-", "_")
        if not attr.isidentifier() or attr in RESERVED:
            continue
        filters = valid_keys(filter_params(operations.get("get", {})))
        fields = valid_keys(create_fields(operations.get("post", {}), components))
        apps[app][attr] = (filters, fields)

    version = spec.get("info", {}).get("version", "unknown")

    apps_chunks = [APPS_HEADER.format(source=url, version=version)]
    hints_chunks = [HINTS_HEADER.format(source=url, version=version)]
    for app in sorted(apps):
        lines = [f"class {app.title()}App(App):"]
        for attr in sorted(apps[app]):
            filters, fields = apps[app][attr]
            hints_chunks.append(endpoint_stub(app, attr, filters, fields))
            lines.append(f"    {attr}: hints.{app.title()}{pascal(attr)}Endpoint")
        apps_chunks.append("\n".join(lines))
    mapping = [f'    "{app}": {app.title()}App,' for app in sorted(apps)]
    apps_chunks.append(
        "APP_CLASSES: dict[str, type[App]] = {\n" + "\n".join(mapping) + "\n}"
    )

    (SRC / "apps_generated.py").write_text("\n\n\n".join(apps_chunks) + "\n")
    (SRC / "hints_generated.pyi").write_text("\n\n\n".join(hints_chunks) + "\n")
    total = sum(len(v) for v in apps.values())
    params = sum(len(f) for v in apps.values() for f, _ in v.values())
    print(
        f"wrote apps_generated.py + hints_generated.pyi ({total} endpoints, {params} filter params, "
        f"NetBox {version})"
    )


main()
